{
  settings = {
    windowrulev2 = [
      "float, class:^(blueberry\.py)$"
      "float, class:^(steam)$"
      "float, class:^(guifetch)$"
      "float, class:^(pavucontrol)$"
      "size 45%, class:^(pavucontrol)$"
      "center, class:^(pavucontrol)$"
      "float, class:^(org.pulseaudio.pavucontrol)$"
      "size 45%, class:^(org.pulseaudio.pavucontrol)$"
      "center, class:^(org.pulseaudio.pavucontrol)$"
      "float, class:^(nm-connection-editor)$"
      "size 45%, class:^(nm-connection-editor)$"
      "center, class:^(nm-connection-editor)$"
      "tile, class:^dev\.warp\.Warp$"
      "float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$"
      "keepaspectratio, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$"
      "move 73% 72%, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$ "
      "size 25%, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$"
      "float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$"
      "pin, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$"
      "center, title:^(Open File)(.*)$"
      "center, title:^(Select a File)(.*)$"
      "center, title:^(Choose wallpaper)(.*)$"
      "center, title:^(Open Folder)(.*)$"
      "center, title:^(Save As)(.*)$"
      "center, title:^(Library)(.*)$"
      "center, title:^(File Upload)(.*)$"
      "float, title:^(Open File)(.*)$"
      "float, title:^(Select a File)(.*)$"
      "float, title:^(Choose wallpaper)(.*)$"
      "float, title:^(Open Folder)(.*)$"
      "float, title:^(Save As)(.*)$"
      "float, title:^(Library)(.*)$"
      "float, title:^(File Upload)(.*)$"
      "immediate, title:.*\.exe"
      "immediate, class:^(steam_app)"
      "noshadow, floating:0"
    ];
    layerrule = [
      "animation slide left, sideleft.*"
      "animation slide right, sideright.*"
      "blur, bar[0-9]*"
      "blur, cheatsheet[0-9]*"
      "blur, barcorner.*"
      "blur, dock[0-9]*"
      "blur, gtk-layer-shell"
      "blur, indicator.*"
      "blur, indicator.*"
      "blur, launcher"
      "blur, notifications"
      "blur, osk[0-9]*"
      "blur, overview[0-9]*"
      "blur, session"
      "blur, shell:*"
      "blur, sideleft[0-9]*"
      "blur, sideright[0-9]*"
      "ignorealpha 0.5, launcher"
      "ignorealpha 0.69, notifications"
      "ignorealpha 0.6, bar[0-9]*"
      "ignorealpha 0.6, barcorner.*"
      "ignorealpha 0.6, cheatsheet[0-9]*"
      "ignorealpha 0.6, dock[0-9]*"
      "ignorealpha 0.6, indicator.*"
      "ignorealpha 0.6, indicator.*"
      "ignorealpha 0.6, osk[0-9]*"
      "ignorealpha 0.6, overview[0-9]*"
      "ignorealpha 0.6, shell:*"
      "ignorealpha 0.6, sideleft[0-9]*"
      "ignorealpha 0.6, sideright[0-9]*"
      "ignorezero, gtk-layer-shell"
      "noanim, anyrun"
      "noanim, hyprpicker"
      "noanim, indicator.*"
      "noanim, noanim"
      "noanim, osk"
      "noanim, overview"
      "noanim, selection"
      "noanim, walker"
      "xray 1, .*"
    ];
  };
}
